version: '3'
services:
    apps:
        container_name: 'farhan-app-thesis'
        build:
            context: ./
            dockerfile: ./etc/docker/apps/Dockerfile
        command: python app.py
        volumes:
            - .:/usr/thesis
    backend:
        container_name: 'farhan-backend-thesis'
        build:
            context: ./
            dockerfile: ./etc/docker/apps/Dockerfile
        command: python server.py
        volumes:
            - .:/usr/thesis
    # notebook:
    #     image: jupyter/tensorflow-notebook:latest
    #     volumes:
    #         - ./public/jupyter-notebook:/home/jovyan/work
    #     ports:
    #         - 8888:8888